server:
  port: 8282
spring:
  datasource:
    driver-class-name: org.h2.Driver # In production use Postgres
    url: jdbc:h2:file:./todos;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
